### ISSUE TITLE
Version not bumped to 4.5.7 in release v4.5.7

### ISSUE THREAD

**Issue by chop-suey** [sqlcipher/sqlcipher-android#36]
It seems like the version has not been bumped in the latest release. E.g.:

- https://github.com/sqlcipher/sqlcipher-android/blob/v4.5.7/README.md
- https://github.com/sqlcipher/sqlcipher-android/blob/v4.5.7/build.gradle#L31

Maybe there are other files as well.

**Comment by developernotes** [comment]
Hi @chop-suey,

The source for SQLCipher core is not included with SQLCipher for Android. As such, our builds utilize `${sqlcipherAndroidVersion}` to communicate the version which is provided externally during a build. We will likely remove the `else` branch in a future release. If you are building from source, you should use `${sqlcipherAndroidVersion}` too.

**Comment by chop-suey** [comment]
Hi @developernotes 

Thanks for your response and pointing this out. I already figured out using of `${sqlcipherAndroidVersion}` but considered it a workaround.
It's fine for me to use this on a regular basis. Is it safe to assume that the version of sqlcipher-android always reflects the version of the used SQLCipher core?

Wouldn't this imply that there can never be a new version of sqlcipher-android if there is no new version of sqlcipher available?

**Comment by developernotes** [comment]
Hi @chop-suey,

No the SQLCipher for Android library could contain changes unrelated to the upstream SQLCipher core. Because SQLCipher for Android utilizes an amalgamation of SQLCipher (ref. [here](https://github.com/sqlcipher/sqlcipher-android/blob/master/sqlcipher/src/main/jni/sqlcipher/Android.mk#L29)) during the build, and SQLCipher for Android doesn't include SQLCipher core within the source repository, one could build SQLCipher for Android with differing versions of SQLCipher, hypothetically. That said, we do release a new version of SQLCipher for Android in conjunction with the SQLCipher core releases.

**Comment by chop-suey** [comment]
Thank you very much for the explanation!
